/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package merl1n.parser;

public interface ParserConstants {

  int EOF = 0;
  int BOOLEAN_LITERAL = 7;
  int INTEGER_LITERAL = 8;
  int REAL_LITERAL = 9;
  int EXPONENT = 10;
  int TEXT_LITERAL = 11;
  int BOOLEAN = 12;
  int INTEGER = 13;
  int REAL = 14;
  int TEXT = 15;
  int ASK = 16;
  int IF = 17;
  int THEN = 18;
  int SEND = 19;
  int PRINT = 20;
  int NL = 21;
  int EXEC = 22;
  int STOP = 23;
  int IMAGE = 24;
  int DOCUMENT = 25;
  int AT = 26;
  int AND = 27;
  int OR = 28;
  int NOT = 29;
  int END = 30;
  int IDENTIFIER = 31;
  int LETTER = 32;
  int DIGIT = 33;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"\\f\"",
    "<token of kind 6>",
    "<BOOLEAN_LITERAL>",
    "<INTEGER_LITERAL>",
    "<REAL_LITERAL>",
    "<EXPONENT>",
    "<TEXT_LITERAL>",
    "\"boolean\"",
    "\"integer\"",
    "\"real\"",
    "\"text\"",
    "\"ask\"",
    "\"if\"",
    "\"then\"",
    "\"send\"",
    "\"print\"",
    "\"nl\"",
    "\"exec\"",
    "\"stop\"",
    "\"image\"",
    "\"document\"",
    "\"at\"",
    "\"and\"",
    "\"or\"",
    "\"not\"",
    "\"end\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\":=\"",
    "\"(\"",
    "\",\"",
    "\")\"",
    "\":\"",
    "\"=\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
  };

}
